"""G-code analysis (design doc §4 Level C, §52-§53 waste).

Two independent sources come out of a G-code file:

  * what the slicer *claims* — comments it writes at the end of the file
  * what the moves actually *contain* — extrusion summed from the E axis

§4 requires storing both and lowering confidence when they disagree, rather
than silently trusting one.

It also works out **waste** without anyone typing it in. Every extrusion move
sits under a `;TYPE:` label, so support, skirt, brim and the start-of-print
prime line can be measured directly. Colour-change purge is harder: on the
Kobra X the firmware purges, so those moves are commented out of the file and
no extrusion count will ever see them. The slicer still states how much it
expects to flush for each pair of filaments (`flush_volumes_matrix`), so purge
is computed from that and from the tool changes the file actually makes.
"""
from __future__ import annotations

import math
import re
from dataclasses import asdict, dataclass, field
from typing import Any, Iterable

# Waste categories, in the order they are reported.
WASTE_KINDS = ("support", "skirt_brim", "prime_line", "purge")


@dataclass
class GcodeResult:
    # Independently computed from E-axis movement: everything deposited,
    # product and printed waste alike. Firmware purge is not in here, which is
    # what keeps it comparable with the slicer's own total.
    calculated_filament_mm: float
    calculated_filament_cm3: float
    calculated_filament_grams: float | None

    # Whatever the slicer wrote in its own comments; None when absent.
    slicer_filament_grams: float | None
    slicer_filament_mm: float | None
    slicer_print_time_seconds: int | None

    layer_count: int
    density_g_cm3: float | None
    max_z_mm: float
    line_count: int
    slicer_name: str | None
    filament_diameter_mm: float
    # Per-tool extrusion, so multi-material plates can be costed per spool.
    per_tool_filament_mm: dict[int, float] = field(default_factory=dict)
    warnings: list[str] = field(default_factory=list)

    # What the slicer says each filament uses, e.g. [3.02, 0.73].
    slicer_filament_grams_per_tool: list[float] = field(default_factory=list)
    tool_changes: int = 0
    # Material the job consumes, split into what ends up in the product and
    # what does not. total_grams = product_grams + waste["total_g"].
    product_grams: float | None = None
    total_grams: float | None = None
    waste: dict[str, Any] = field(default_factory=dict)
    per_tool: list[dict[str, Any]] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        data = asdict(self)
        data["per_tool_filament_mm"] = {str(k): v for k, v in self.per_tool_filament_mm.items()}
        return data


# Slicers write their totals as comments in varying formats. These cover
# OrcaSlicer / Bambu / Prusa / Cura, which is the lineage the doc targets.
_TOTAL_GRAMS_PATTERNS = [
    re.compile(r";\s*total filament used \[g\]\s*[:=]\s*([\d.]+)", re.I),
    re.compile(r";\s*filament_weight_total\s*[:=]\s*([\d.]+)", re.I),
]
# Per filament: "; filament used [g] = 3.02, 0.73" on a two-colour print.
_PER_TOOL_GRAMS_PATTERN = re.compile(r";\s*filament used \[g\]\s*[:=]\s*([\d.,\s]+)$", re.I)
_CURA_GRAMS_PATTERN = re.compile(r";\s*Filament used:\s*([\d.]+)\s*g", re.I)
_MM_PATTERNS = [
    re.compile(r";\s*filament used \[mm\]\s*[:=]\s*([\d.,\s]+)$", re.I),
    re.compile(r";\s*Filament used:\s*([\d.]+)\s*m\b", re.I),
]
_TIME_PATTERNS = [
    re.compile(r";\s*estimated printing time.*?[:=]\s*(.+)", re.I),
    re.compile(r";\s*TIME\s*[:=]\s*(\d+)", re.I),
    re.compile(r";\s*model printing time\s*[:=]\s*(.+)", re.I),
]
_DIAMETER_PATTERN = re.compile(r";\s*filament_diameter\s*[:=]\s*([\d.,\s]+)$", re.I)
_DENSITY_PATTERN = re.compile(r";\s*filament_density\s*[:=]\s*([\d.,\s]+)$", re.I)
# Slicers state the layer total outright; counting Z rises instead turns every
# retraction z-hop into a phantom layer.
_TOTAL_LAYERS_PATTERN = re.compile(r";\s*total layer number\s*[:=]\s*(\d+)", re.I)
_LAYER_CHANGE_MARKER = re.compile(r"^;\s*(?:LAYER_CHANGE|CHANGE_LAYER)", re.I)
_GENERATOR_PATTERN = re.compile(r";\s*(?:generated by|Generated with)\s+(.+)", re.I)
_LAYER_COMMENT = re.compile(r";\s*(?:LAYER|layer)\s*[:=]?\s*(\d+)")
_TYPE_PATTERN = re.compile(r"^;\s*TYPE\s*:\s*(.+)$", re.I)
_FLUSH_MATRIX_PATTERN = re.compile(r";\s*flush_volumes_matrix\s*[:=]\s*([\d.,\s]+)$", re.I)
_FLUSH_MULTIPLIER_PATTERN = re.compile(r";\s*flush_multiplier\s*[:=]\s*([\d.,\s]+)$", re.I)

_DURATION = re.compile(r"(?:(\d+)\s*d)?\s*(?:(\d+)\s*h)?\s*(?:(\d+)\s*m)?\s*(?:(\d+)\s*s)?", re.I)


def _to_float(text: str) -> float | None:
    try:
        return float(text.strip().replace(",", ""))
    except (TypeError, ValueError):
        return None


def _to_floats(text: str) -> list[float]:
    """"3.02, 0.73" -> [3.02, 0.73]. Orca and Bambu never use thousands commas."""
    values = []
    for part in text.split(","):
        part = part.strip()
        if not part:
            continue
        try:
            values.append(float(part))
        except ValueError:
            return []
    return values


def _waste_kind(role: str) -> str | None:
    """Which waste category a `;TYPE:` label belongs to; None means product."""
    name = role.strip().lower()
    if name.startswith("support"):
        return "support"
    if name in ("skirt", "brim"):
        return "skirt_brim"
    if name in ("prime tower", "wipe tower"):
        return "purge"
    if name == "custom":
        # Start and end G-code. The only extrusion in it is the prime line
        # drawn at the edge of the bed before the print starts.
        return "prime_line"
    return None


def parse_duration(text: str) -> int | None:
    """Parse '2d 3h 51m 12s' or '10230' into seconds."""
    text = text.strip()
    if text.isdigit():
        return int(text)

    match = _DURATION.search(text)
    if not match or not any(match.groups()):
        return None
    days, hours, minutes, seconds = (int(g) if g else 0 for g in match.groups())
    total = days * 86400 + hours * 3600 + minutes * 60 + seconds
    return total or None


def parse_gcode(lines: Iterable[str], default_density_g_cm3: float | None = 1.24) -> GcodeResult:
    """Sum real extrusion by tool and feature while collecting what the slicer declared."""
    absolute_e = True
    last_e = 0.0
    tool = 0
    current_tool: int | None = None
    tool_changes: list[tuple[int, int]] = []
    per_tool: dict[int, float] = {}
    extruded_mm = 0.0
    # Filament currently pulled back. A retraction is not consumption, and the
    # positive move that pushes it back in is not consumption either — it only
    # restores what was withdrawn. Counting those un-retracts as new material
    # overstated a real print by 39%.
    retracted_mm = 0.0

    # Deposited filament by tool and category. "untyped" collects moves made
    # before any ;TYPE: label; what it means is decided once the whole file has
    # been read (see below).
    role: str | None = None
    saw_type_labels = False
    by_tool_kind: dict[int, dict[str, float]] = {}

    max_z = 0.0
    current_z = 0.0
    layer_changes = 0
    layer_change_markers = 0
    declared_layers: int | None = None
    layer_comment_max: int | None = None
    line_count = 0

    diameters: list[float] = []
    # The slicer states the density it costed with; using ours instead would
    # make the two figures disagree for a reason that is not a real error.
    densities: list[float] = []
    slicer_name: str | None = None
    slicer_total_grams: float | None = None
    slicer_grams_per_tool: list[float] = []
    cura_grams: float | None = None
    slicer_mm: float | None = None
    slicer_seconds: int | None = None
    flush_matrix: list[float] = []
    flush_multiplier = 1.0
    warnings: list[str] = []

    for raw in lines:
        line_count += 1
        line = raw.strip()
        if not line:
            continue

        if line.startswith(";"):
            m = _TYPE_PATTERN.match(line)
            if m:
                role = m.group(1)
                saw_type_labels = True
                continue
            if slicer_total_grams is None:
                for pattern in _TOTAL_GRAMS_PATTERNS:
                    m = pattern.search(line)
                    if m:
                        slicer_total_grams = _to_float(m.group(1))
                        break
            if not slicer_grams_per_tool:
                m = _PER_TOOL_GRAMS_PATTERN.search(line)
                if m:
                    slicer_grams_per_tool = _to_floats(m.group(1))
            if cura_grams is None:
                m = _CURA_GRAMS_PATTERN.search(line)
                if m:
                    cura_grams = _to_float(m.group(1))
            if slicer_mm is None:
                for pattern in _MM_PATTERNS:
                    m = pattern.search(line)
                    if m:
                        values = _to_floats(m.group(1))
                        if values:
                            # "Filament used: 12.5m" is metres, not millimetres.
                            total = sum(values)
                            slicer_mm = total * 1000.0 if re.search(r"\dm\b", line) else total
                        break
            if slicer_seconds is None:
                for pattern in _TIME_PATTERNS:
                    m = pattern.search(line)
                    if m:
                        slicer_seconds = parse_duration(m.group(1))
                        break
            if slicer_name is None:
                m = _GENERATOR_PATTERN.search(line)
                if m:
                    slicer_name = m.group(1).strip()
            m = _DIAMETER_PATTERN.search(line)
            if m:
                values = [v for v in _to_floats(m.group(1)) if v > 0]
                if values:
                    diameters = values
            m = _DENSITY_PATTERN.search(line)
            if m:
                values = [v for v in _to_floats(m.group(1)) if v > 0]
                if values:
                    densities = values
            m = _FLUSH_MATRIX_PATTERN.search(line)
            if m:
                flush_matrix = _to_floats(m.group(1))
            m = _FLUSH_MULTIPLIER_PATTERN.search(line)
            if m:
                values = _to_floats(m.group(1))
                if values:
                    flush_multiplier = values[0]
            m = _TOTAL_LAYERS_PATTERN.search(line)
            if m:
                declared_layers = int(m.group(1))
            elif _LAYER_CHANGE_MARKER.match(line):
                layer_change_markers += 1
            else:
                m = _LAYER_COMMENT.search(line)
                if m:
                    index = int(m.group(1))
                    layer_comment_max = (
                        index if layer_comment_max is None else max(layer_comment_max, index)
                    )
            continue

        # Strip trailing comments from a command line.
        code = line.split(";", 1)[0].strip()
        if not code:
            continue

        upper = code.upper()

        if upper.startswith("M82"):
            absolute_e = True
            continue
        if upper.startswith("M83"):
            absolute_e = False
            continue
        if upper.startswith("G92"):
            m = re.search(r"E(-?[\d.]+)", upper)
            if m:
                last_e = float(m.group(1))
            continue
        if re.fullmatch(r"T(\d+)", upper):
            tool = int(upper[1:])
            # The first T only selects a filament. Every later switch to a
            # different one is a colour change that has to be purged.
            if current_tool is not None and tool != current_tool:
                tool_changes.append((current_tool, tool))
            current_tool = tool
            continue

        if not re.match(r"G[0-3](\D|$)", upper):
            continue

        z_match = re.search(r"Z(-?[\d.]+)", upper)
        if z_match:
            new_z = float(z_match.group(1))
            if new_z > current_z:
                layer_changes += 1
            current_z = new_z
            max_z = max(max_z, new_z)

        e_match = re.search(r"E(-?[\d.]+)", upper)
        if e_match:
            value = float(e_match.group(1))
            if absolute_e:
                delta = value - last_e
                last_e = value
            else:
                delta = value
            if delta < 0:
                # Withdrawing filament; remember how much is owed back.
                retracted_mm += -delta
            elif delta > 0:
                # Repay the outstanding retraction first; only the surplus is
                # material actually laid down.
                repaid = min(delta, retracted_mm)
                retracted_mm -= repaid
                deposited = delta - repaid
                if deposited > 0:
                    extruded_mm += deposited
                    per_tool[tool] = per_tool.get(tool, 0.0) + deposited
                    kind = "untyped" if role is None else (_waste_kind(role) or "product")
                    bucket = by_tool_kind.setdefault(tool, {})
                    bucket[kind] = bucket.get(kind, 0.0) + deposited

    # Moves before the first ;TYPE: label. In a file that labels its features,
    # that can only be priming before the print; in one that labels nothing,
    # it is simply the print, and calling it waste would be absurd.
    for bucket in by_tool_kind.values():
        untyped = bucket.pop("untyped", 0.0)
        if untyped:
            key = "prime_line" if saw_type_labels else "product"
            bucket[key] = bucket.get(key, 0.0) + untyped

    default_diameter = 1.75
    diameter = diameters[0] if diameters else default_diameter
    density = (densities[0] if densities else None) or default_density_g_cm3

    def tool_diameter(t: int) -> float:
        return diameters[t] if t < len(diameters) else diameter

    def tool_density(t: int) -> float | None:
        return densities[t] if t < len(densities) else density

    def mm_to_grams(mm: float, t: int) -> float | None:
        d = tool_density(t)
        if d is None:
            return None
        radius_cm = tool_diameter(t) / 2.0 / 10.0
        return math.pi * radius_cm * radius_cm * (mm / 10.0) * d

    # Purge. A prime tower is printed, so it was measured above. Without one,
    # the printer purges on its own and the only record is the slicer's flush
    # table, indexed [from * filaments + to].
    measured_purge_mm = sum(b.get("purge", 0.0) for b in by_tool_kind.values())
    purge_grams_by_tool: dict[int, float] = {}
    purge_basis = "none"
    if measured_purge_mm > 0:
        purge_basis = "prime tower"
    elif tool_changes:
        size = int(round(math.sqrt(len(flush_matrix)))) if flush_matrix else 0
        if size and size * size == len(flush_matrix):
            purge_basis = "flush volumes"
            for source, target in tool_changes:
                if source < size and target < size:
                    volume_mm3 = flush_matrix[source * size + target] * flush_multiplier
                    d = tool_density(target)
                    if d is not None and volume_mm3 > 0:
                        # The incoming filament is what pushes the old one out,
                        # so the purge comes off the new colour's spool.
                        purge_grams_by_tool[target] = (
                            purge_grams_by_tool.get(target, 0.0) + volume_mm3 / 1000.0 * d
                        )
        else:
            purge_basis = "unknown"
            warnings.append(
                f"{len(tool_changes)} colour change(s) found but the slicer stated no flush "
                "volumes, so purge waste is not counted."
            )

    radius_cm = (diameter / 2.0) / 10.0
    volume_cm3 = math.pi * radius_cm * radius_cm * (extruded_mm / 10.0)
    grams = round(volume_cm3 * density, 3) if density else None

    # Per tool: product and each waste kind, in grams.
    tools = sorted(set(by_tool_kind) | set(purge_grams_by_tool))
    breakdown: list[dict[str, Any]] = []
    totals = {kind: 0.0 for kind in WASTE_KINDS}
    product_total = 0.0
    known = density is not None
    for t in tools:
        bucket = by_tool_kind.get(t, {})
        row: dict[str, Any] = {"tool": t}
        product_g = mm_to_grams(bucket.get("product", 0.0), t) or 0.0
        row["product_g"] = round(product_g, 3)
        waste_g = 0.0
        for kind in WASTE_KINDS:
            value = (mm_to_grams(bucket.get(kind, 0.0), t) or 0.0)
            if kind == "purge":
                value += purge_grams_by_tool.get(t, 0.0)
            row[f"{kind}_g"] = round(value, 3)
            totals[kind] += value
            waste_g += value
        row["waste_g"] = round(waste_g, 3)
        row["total_g"] = round(product_g + waste_g, 3)
        product_total += product_g
        breakdown.append(row)

    waste_total = sum(totals.values())
    waste_summary: dict[str, Any] = {f"{k}_g": round(v, 3) for k, v in totals.items()}
    waste_summary["total_g"] = round(waste_total, 3)
    waste_summary["purge_basis"] = purge_basis
    waste_summary["tool_changes"] = len(tool_changes)

    # A total from the slicer beats summing its per-filament figures, which
    # are rounded to two places each.
    slicer_grams = slicer_total_grams
    if slicer_grams is None and slicer_grams_per_tool:
        slicer_grams = round(sum(slicer_grams_per_tool), 3)
    if slicer_grams is None:
        slicer_grams = cura_grams

    if declared_layers is not None:
        layer_count = declared_layers
    elif layer_change_markers > 0:
        layer_count = layer_change_markers
    elif layer_comment_max is not None:
        layer_count = layer_comment_max + 1
    else:
        layer_count = layer_changes

    if extruded_mm <= 0:
        warnings.append("No extrusion found; the file may be a travel-only or empty program.")
    if slicer_grams is None and slicer_seconds is None:
        warnings.append("No slicer summary comments found; only calculated values are available.")

    return GcodeResult(
        calculated_filament_mm=round(extruded_mm, 3),
        calculated_filament_cm3=round(volume_cm3, 4),
        calculated_filament_grams=grams,
        slicer_filament_grams=slicer_grams,
        slicer_filament_mm=slicer_mm,
        slicer_print_time_seconds=slicer_seconds,
        layer_count=layer_count,
        density_g_cm3=density,
        max_z_mm=round(max_z, 3),
        line_count=line_count,
        slicer_name=slicer_name,
        filament_diameter_mm=diameter,
        per_tool_filament_mm={k: round(v, 3) for k, v in per_tool.items()},
        warnings=warnings,
        slicer_filament_grams_per_tool=slicer_grams_per_tool,
        tool_changes=len(tool_changes),
        product_grams=round(product_total, 3) if known else None,
        total_grams=round(product_total + waste_total, 3) if known else None,
        waste=waste_summary,
        per_tool=breakdown,
    )


def confidence_from_agreement(
    calculated_grams: float | None,
    slicer_grams: float | None,
    tolerance: float = 0.05,
) -> tuple[str, str]:
    """Confidence rating from §82, based on whether the two sources agree.

    Returns (level, reason). Agreement within tolerance is HIGH; disagreement
    is MEDIUM with the gap stated, because silently trusting either number is
    exactly what §4 forbids.
    """
    if slicer_grams is None and calculated_grams is None:
        return "LOW", "No filament figure could be determined."
    if slicer_grams is None:
        return "MEDIUM", "Only the G-code calculation is available; the slicer reported nothing."
    if calculated_grams is None:
        return "MEDIUM", "Only the slicer figure is available."
    if slicer_grams <= 0:
        return "LOW", "Slicer reported zero filament."

    difference = abs(calculated_grams - slicer_grams) / slicer_grams
    if difference <= tolerance:
        return "HIGH", (
            f"Slicer and G-code agree within {difference * 100:.1f}% "
            f"({slicer_grams:.2f} g vs {calculated_grams:.2f} g)."
        )
    return "MEDIUM", (
        f"Slicer and G-code disagree by {difference * 100:.1f}% "
        f"({slicer_grams:.2f} g vs {calculated_grams:.2f} g)."
    )
