"""G-code analysis (design doc §4 Level C).

Two independent sources come out of a G-code file:

  * what the slicer *claims* — comments it writes at the end of the file
  * what the moves actually *contain* — extrusion summed from the E axis

§4 requires storing both and lowering confidence when they disagree, rather
than silently trusting one. That is the whole point of this module.
"""
from __future__ import annotations

import math
import re
from dataclasses import dataclass, field, asdict
from typing import Any, Iterable


@dataclass
class GcodeResult:
    # Independently computed from E-axis movement.
    calculated_filament_mm: float
    calculated_filament_cm3: float
    calculated_filament_grams: float | None

    # Whatever the slicer wrote in its own comments; None when absent.
    slicer_filament_grams: float | None
    slicer_filament_mm: float | None
    slicer_print_time_seconds: int | None

    layer_count: int
    density_g_cm3: float | None
    max_z_mm: float
    line_count: int
    slicer_name: str | None
    filament_diameter_mm: float
    # Per-tool extrusion, so multi-material plates can be costed per spool.
    per_tool_filament_mm: dict[int, float] = field(default_factory=dict)
    warnings: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        data = asdict(self)
        data["per_tool_filament_mm"] = {str(k): v for k, v in self.per_tool_filament_mm.items()}
        return data


# Slicers write their totals as comments in varying formats. These cover
# OrcaSlicer / Bambu / Prusa / Cura, which is the lineage the doc targets.
_GRAMS_PATTERNS = [
    re.compile(r";\s*filament used \[g\]\s*[:=]\s*([\d.,]+)", re.I),
    re.compile(r";\s*total filament used \[g\]\s*[:=]\s*([\d.,]+)", re.I),
    re.compile(r";\s*filament_weight_total\s*[:=]\s*([\d.,]+)", re.I),
    re.compile(r";\s*Filament used:\s*([\d.]+)\s*g", re.I),
]
_MM_PATTERNS = [
    re.compile(r";\s*filament used \[mm\]\s*[:=]\s*([\d.,]+)", re.I),
    re.compile(r";\s*Filament used:\s*([\d.]+)\s*m\b", re.I),
]
_TIME_PATTERNS = [
    re.compile(r";\s*estimated printing time.*?[:=]\s*(.+)", re.I),
    re.compile(r";\s*TIME\s*[:=]\s*(\d+)", re.I),
    re.compile(r";\s*model printing time\s*[:=]\s*(.+)", re.I),
]
_DIAMETER_PATTERN = re.compile(r";\s*filament_diameter\s*[:=]\s*([\d.]+)", re.I)
_DENSITY_PATTERN = re.compile(r";\s*filament_density\s*[:=]\s*([\d.]+)", re.I)
_GENERATOR_PATTERN = re.compile(r";\s*(?:generated by|Generated with)\s+(.+)", re.I)
_LAYER_COMMENT = re.compile(r";\s*(?:LAYER|layer)\s*[:=]?\s*(\d+)")

_DURATION = re.compile(r"(?:(\d+)\s*d)?\s*(?:(\d+)\s*h)?\s*(?:(\d+)\s*m)?\s*(?:(\d+)\s*s)?", re.I)


def _to_float(text: str) -> float | None:
    try:
        return float(text.strip().replace(",", ""))
    except (TypeError, ValueError):
        return None


def parse_duration(text: str) -> int | None:
    """Parse '2d 3h 51m 12s' or '10230' into seconds."""
    text = text.strip()
    if text.isdigit():
        return int(text)

    match = _DURATION.search(text)
    if not match or not any(match.groups()):
        return None
    days, hours, minutes, seconds = (int(g) if g else 0 for g in match.groups())
    total = days * 86400 + hours * 3600 + minutes * 60 + seconds
    return total or None


def parse_gcode(lines: Iterable[str], default_density_g_cm3: float | None = 1.24) -> GcodeResult:
    """Sum real extrusion while collecting whatever the slicer declared.

    Only G0/G1/G2/G3 moves count. Retractions are negative E and must not be
    subtracted from the total — filament pulled back is pushed out again, so
    counting them would understate usage.
    """
    absolute_e = True
    last_e = 0.0
    tool = 0
    per_tool: dict[int, float] = {}
    extruded_mm = 0.0

    max_z = 0.0
    current_z = 0.0
    layer_changes = 0
    layer_comment_max: int | None = None
    line_count = 0

    diameter = 1.75
    # The slicer states the density it costed with; using ours instead would
    # make the two figures disagree for a reason that is not a real error.
    declared_density: float | None = None
    slicer_name: str | None = None
    slicer_grams: float | None = None
    slicer_mm: float | None = None
    slicer_seconds: int | None = None
    warnings: list[str] = []

    for raw in lines:
        line_count += 1
        line = raw.strip()
        if not line:
            continue

        if line.startswith(";"):
            if slicer_grams is None:
                for pattern in _GRAMS_PATTERNS:
                    m = pattern.search(line)
                    if m:
                        slicer_grams = _to_float(m.group(1))
                        break
            if slicer_mm is None:
                for pattern in _MM_PATTERNS:
                    m = pattern.search(line)
                    if m:
                        value = _to_float(m.group(1))
                        if value is not None:
                            # "Filament used: 12.5m" is metres, not millimetres.
                            slicer_mm = value * 1000.0 if re.search(r"\dm\b", line) else value
                        break
            if slicer_seconds is None:
                for pattern in _TIME_PATTERNS:
                    m = pattern.search(line)
                    if m:
                        slicer_seconds = parse_duration(m.group(1))
                        break
            if slicer_name is None:
                m = _GENERATOR_PATTERN.search(line)
                if m:
                    slicer_name = m.group(1).strip()
            m = _DIAMETER_PATTERN.search(line)
            if m:
                value = _to_float(m.group(1))
                if value:
                    diameter = value
            m = _DENSITY_PATTERN.search(line)
            if m:
                value = _to_float(m.group(1))
                if value:
                    declared_density = value
            m = _LAYER_COMMENT.search(line)
            if m:
                index = int(m.group(1))
                layer_comment_max = index if layer_comment_max is None else max(layer_comment_max, index)
            continue

        # Strip trailing comments from a command line.
        code = line.split(";", 1)[0].strip()
        if not code:
            continue

        upper = code.upper()

        if upper.startswith("M82"):
            absolute_e = True
            continue
        if upper.startswith("M83"):
            absolute_e = False
            continue
        if upper.startswith("G92"):
            m = re.search(r"E(-?[\d.]+)", upper)
            if m:
                last_e = float(m.group(1))
            continue
        if re.fullmatch(r"T(\d+)", upper):
            tool = int(upper[1:])
            continue

        if not re.match(r"G[0-3](\D|$)", upper):
            continue

        z_match = re.search(r"Z(-?[\d.]+)", upper)
        if z_match:
            new_z = float(z_match.group(1))
            if new_z > current_z:
                layer_changes += 1
            current_z = new_z
            max_z = max(max_z, new_z)

        e_match = re.search(r"E(-?[\d.]+)", upper)
        if e_match:
            value = float(e_match.group(1))
            if absolute_e:
                delta = value - last_e
                last_e = value
            else:
                delta = value
            # Negative delta is a retraction, not consumption.
            if delta > 0:
                extruded_mm += delta
                per_tool[tool] = per_tool.get(tool, 0.0) + delta

    radius_cm = (diameter / 2.0) / 10.0
    volume_cm3 = math.pi * radius_cm * radius_cm * (extruded_mm / 10.0)
    density = declared_density or default_density_g_cm3
    grams = round(volume_cm3 * density, 3) if density else None

    layer_count = layer_comment_max + 1 if layer_comment_max is not None else layer_changes

    if extruded_mm <= 0:
        warnings.append("No extrusion found; the file may be a travel-only or empty program.")
    if slicer_grams is None and slicer_seconds is None:
        warnings.append("No slicer summary comments found; only calculated values are available.")

    return GcodeResult(
        calculated_filament_mm=round(extruded_mm, 3),
        calculated_filament_cm3=round(volume_cm3, 4),
        calculated_filament_grams=grams,
        slicer_filament_grams=slicer_grams,
        slicer_filament_mm=slicer_mm,
        slicer_print_time_seconds=slicer_seconds,
        layer_count=layer_count,
        density_g_cm3=density,
        max_z_mm=round(max_z, 3),
        line_count=line_count,
        slicer_name=slicer_name,
        filament_diameter_mm=diameter,
        per_tool_filament_mm={k: round(v, 3) for k, v in per_tool.items()},
        warnings=warnings,
    )


def confidence_from_agreement(
    calculated_grams: float | None,
    slicer_grams: float | None,
    tolerance: float = 0.05,
) -> tuple[str, str]:
    """Confidence rating from §82, based on whether the two sources agree.

    Returns (level, reason). Agreement within tolerance is HIGH; disagreement
    is MEDIUM with the gap stated, because silently trusting either number is
    exactly what §4 forbids.
    """
    if slicer_grams is None and calculated_grams is None:
        return "LOW", "No filament figure could be determined."
    if slicer_grams is None:
        return "MEDIUM", "Only the G-code calculation is available; the slicer reported nothing."
    if calculated_grams is None:
        return "MEDIUM", "Only the slicer figure is available."
    if slicer_grams <= 0:
        return "LOW", "Slicer reported zero filament."

    difference = abs(calculated_grams - slicer_grams) / slicer_grams
    if difference <= tolerance:
        return "HIGH", (
            f"Slicer and G-code agree within {difference * 100:.1f}% "
            f"({slicer_grams:.2f} g vs {calculated_grams:.2f} g)."
        )
    return "MEDIUM", (
        f"Slicer and G-code disagree by {difference * 100:.1f}% "
        f"({slicer_grams:.2f} g vs {calculated_grams:.2f} g)."
    )
