"""G-code parser tests.

The extrusion total is the number that eventually becomes money, so these check
it against hand-computed values rather than whatever the parser produces.
"""
from __future__ import annotations

import math

import pytest

from app.gcode.parser import confidence_from_agreement, parse_duration, parse_gcode


def filament_grams(length_mm: float, diameter_mm: float = 1.75, density: float = 1.24) -> float:
    radius_cm = (diameter_mm / 2) / 10
    return math.pi * radius_cm**2 * (length_mm / 10) * density


ABSOLUTE = """
; generated by OrcaSlicer 2.1.0
; filament_diameter = 1.75
M82
G1 X0 Y0 Z0.2 F3000
G1 X10 Y0 E1000.0
G1 X20 Y0 E2500.0
G1 Z0.4
G1 X30 Y0 E4000.0
; filament used [g] = 11.9
; estimated printing time (normal mode) = 1h 2m 3s
""".strip().splitlines()


def test_absolute_extrusion_totals():
    result = parse_gcode(ABSOLUTE)
    # Absolute E ends at 4000, having started from 0. Lengths are realistic
    # here because grams are rounded to 3dp: at toy lengths the rounding, not
    # the arithmetic, would decide whether the test passes.
    assert result.calculated_filament_mm == pytest.approx(4000.0)
    assert result.calculated_filament_grams == pytest.approx(filament_grams(4000.0), rel=1e-3)
    assert result.slicer_name == "OrcaSlicer 2.1.0"
    assert result.slicer_print_time_seconds == 3723
    assert result.layer_count == 2


RELATIVE = """
M83
G1 X10 E0.5
G1 X20 E0.5
G1 X30 E0.5
""".strip().splitlines()


def test_relative_extrusion_sums_each_move():
    result = parse_gcode(RELATIVE)
    assert result.calculated_filament_mm == pytest.approx(1.5)


RETRACTION = """
M83
G1 X10 E1.0
G1 E-5.0
G1 E5.0
G1 X20 E1.0
""".strip().splitlines()


def test_retractions_are_not_subtracted():
    """Filament pulled back is pushed out again.

    Netting retraction against extrusion would understate usage; counting the
    unretract as consumption would overstate it. Only positive deltas count, so
    the total here is 1.0 + 5.0 + 1.0.
    """
    result = parse_gcode(RETRACTION)
    assert result.calculated_filament_mm == pytest.approx(7.0)


def test_g92_reset_does_not_create_phantom_extrusion():
    lines = """
M82
G1 X10 E5.0
G92 E0
G1 X20 E5.0
""".strip().splitlines()
    # Without honouring G92 the second move would look like -5 or +10.
    assert parse_gcode(lines).calculated_filament_mm == pytest.approx(10.0)


def test_per_tool_totals_for_multi_material():
    lines = """
M83
T0
G1 X10 E2.0
T1
G1 X20 E3.0
T0
G1 X30 E1.0
""".strip().splitlines()
    result = parse_gcode(lines)
    assert result.per_tool_filament_mm == {0: pytest.approx(3.0), 1: pytest.approx(3.0)}
    assert result.calculated_filament_mm == pytest.approx(6.0)


def test_travel_only_file_warns():
    result = parse_gcode(["G1 X10 Y10", "G1 X20 Y20"])
    assert result.calculated_filament_mm == 0
    assert any("no extrusion" in w.lower() for w in result.warnings)


def test_comments_do_not_count_as_moves():
    result = parse_gcode(["; G1 X10 E99.0", "G1 X10 E1.0 ; E5.0 in a comment", "M83"])
    assert result.calculated_filament_mm == pytest.approx(1.0)


class TestDuration:
    @pytest.mark.parametrize(
        "text,expected",
        [
            ("1h 2m 3s", 3723),
            ("2d 3h", 183600),
            ("45m", 2700),
            ("90", 90),
            ("nonsense", None),
        ],
    )
    def test_parse(self, text, expected):
        assert parse_duration(text) == expected


class TestConfidence:
    def test_close_agreement_is_high(self):
        level, reason = confidence_from_agreement(83.2, 83.5)
        assert level == "HIGH"
        assert "agree" in reason

    def test_disagreement_is_medium_and_states_the_gap(self):
        level, reason = confidence_from_agreement(83.2, 100.0)
        assert level == "MEDIUM"
        assert "%" in reason

    def test_missing_slicer_figure_is_medium(self):
        level, _ = confidence_from_agreement(83.2, None)
        assert level == "MEDIUM"

    def test_nothing_available_is_low(self):
        level, _ = confidence_from_agreement(None, None)
        assert level == "LOW"
