"""Profile resolution and 3MF inspection."""
from __future__ import annotations

import json
import zipfile

import pytest

from app.slicer.profiles import _load_chain, _pick, ProfileError
from app.three_mf.reader import inspect_3mf, read_embedded_gcode


class TestProfileMatching:
    """Regression tests for the substring bug.

    Matching "Kobra X" with a plain `in` test selected "Anycubic Kobra 2 Max",
    because the single letter x occurs inside "Max". That silently sliced on the
    wrong machine, producing a confidently wrong filament and time figure — the
    worst kind of failure for a costing system.
    """

    @pytest.fixture
    def machines(self, tmp_path):
        directory = tmp_path / "machine"
        directory.mkdir()
        for name in [
            "Anycubic Kobra X 0.4 nozzle",
            "Anycubic Kobra 2 Max 0.4 nozzle",
            "Anycubic Kobra 3 Max 0.4 nozzle",
            "Anycubic Kobra S1 0.4 nozzle",
        ]:
            (directory / f"{name}.json").write_text("{}", encoding="utf-8")
        return directory

    def test_single_letter_model_does_not_match_inside_a_word(self, machines):
        assert _pick(machines, ["Kobra X 0.4 nozzle"]) == "Anycubic Kobra X 0.4 nozzle"

    def test_max_variants_still_resolve(self, machines):
        assert _pick(machines, ["Kobra 2 Max 0.4 nozzle"]) == "Anycubic Kobra 2 Max 0.4 nozzle"

    def test_unknown_printer_returns_none(self, machines):
        assert _pick(machines, ["Ender 3"]) is None

    def test_alphanumeric_model_names_are_exact(self, machines):
        assert _pick(machines, ["Kobra S1 0.4 nozzle"]) == "Anycubic Kobra S1 0.4 nozzle"


class TestProfileFlattening:
    def test_child_overrides_parent(self, tmp_path):
        (tmp_path / "base.json").write_text(
            json.dumps({"layer_height": "0.2", "shared": "parent"}), encoding="utf-8"
        )
        (tmp_path / "child.json").write_text(
            json.dumps({"inherits": "base", "shared": "child"}), encoding="utf-8"
        )
        merged = _load_chain(tmp_path, "child")

        assert merged["shared"] == "child"
        assert merged["layer_height"] == "0.2"   # inherited
        assert "inherits" not in merged          # or the CLI re-resolves it

    def test_cli_fixup_makes_the_inert_value_legal(self, tmp_path):
        # Orca range-checks this to [10, 18] even when the feature is disabled,
        # and the stock Anycubic profiles ship 0, which fails to slice.
        (tmp_path / "m.json").write_text(
            json.dumps({"retraction_distances_when_cut": ["0"]}), encoding="utf-8"
        )
        merged = _load_chain(tmp_path, "m")
        assert merged["retraction_distances_when_cut"] == ["10"]

    def test_circular_inheritance_is_rejected(self, tmp_path):
        (tmp_path / "a.json").write_text(json.dumps({"inherits": "b"}), encoding="utf-8")
        (tmp_path / "b.json").write_text(json.dumps({"inherits": "a"}), encoding="utf-8")
        with pytest.raises(ProfileError, match="circular"):
            _load_chain(tmp_path, "a")

    def test_missing_profile_is_reported(self, tmp_path):
        with pytest.raises(ProfileError, match="not found"):
            _load_chain(tmp_path, "nope")


MODEL_XML = """<?xml version="1.0" encoding="UTF-8"?>
<model unit="millimeter" xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02">
  <metadata name="Title">Probe</metadata>
  <metadata name="Application">CrafCube</metadata>
  <resources>
    <object id="1" type="model"/>
    <object id="2" type="model"/>
  </resources>
</model>
"""

SLICED_GCODE = """; generated by OrcaSlicer 2.4.2
; filament_diameter = 1.75
; filament_density = 1.24
M83
G1 X10 E4000
; filament used [g] = 11.9
; estimated printing time (normal mode) = 1h 0m 0s
"""


def make_3mf(path, *, with_gcode=False, unit="millimeter"):
    with zipfile.ZipFile(path, "w") as archive:
        archive.writestr("3D/3dmodel.model", MODEL_XML.replace('unit="millimeter"', f'unit="{unit}"'))
        archive.writestr("[Content_Types].xml", "<Types/>")
        if with_gcode:
            archive.writestr("Metadata/plate_1.gcode", SLICED_GCODE)
            archive.writestr("Metadata/project_settings.config", "layer_height = 0.2\nsparse_infill_density = 15%")
    return path


class TestThreeMf:
    def test_plain_3mf_is_described(self, tmp_path):
        info = inspect_3mf(make_3mf(tmp_path / "a.3mf"))
        assert info.is_zip and info.has_model_part
        assert info.object_count == 2
        assert info.unit == "millimeter"
        assert info.metadata["Title"] == "Probe"
        assert not info.contains_gcode

    def test_sliced_3mf_yields_slicer_figures(self, tmp_path):
        """§41 ranks embedded slicer data above anything we can recompute."""
        info = inspect_3mf(make_3mf(tmp_path / "b.3mf", with_gcode=True))
        assert info.contains_gcode
        assert info.filament_used_grams == pytest.approx(11.9)
        assert info.print_time_seconds == 3600
        assert info.settings["layer_height"] == "0.2"

    def test_non_millimetre_unit_warns(self, tmp_path):
        # A metre-unit model would misprice by a factor of a thousand.
        info = inspect_3mf(make_3mf(tmp_path / "c.3mf", unit="meter"))
        assert any("unit" in w.lower() for w in info.warnings)

    def test_non_zip_is_rejected(self, tmp_path):
        path = tmp_path / "d.3mf"
        path.write_bytes(b"not a zip")
        info = inspect_3mf(path)
        assert not info.is_zip
        assert info.warnings

    def test_embedded_gcode_can_be_read_back(self, tmp_path):
        text = read_embedded_gcode(make_3mf(tmp_path / "e.3mf", with_gcode=True))
        assert text is not None and "OrcaSlicer" in text

    def test_no_gcode_returns_none(self, tmp_path):
        assert read_embedded_gcode(make_3mf(tmp_path / "f.3mf")) is None
