"""G-code parser tests.

The extrusion total is the number that eventually becomes money, so these check
it against hand-computed values rather than whatever the parser produces.
"""
from __future__ import annotations

import math

import pytest

from app.gcode.parser import confidence_from_agreement, parse_duration, parse_gcode


def filament_grams(length_mm: float, diameter_mm: float = 1.75, density: float = 1.24) -> float:
    radius_cm = (diameter_mm / 2) / 10
    return math.pi * radius_cm**2 * (length_mm / 10) * density


ABSOLUTE = """
; generated by OrcaSlicer 2.1.0
; filament_diameter = 1.75
M82
G1 X0 Y0 Z0.2 F3000
G1 X10 Y0 E1000.0
G1 X20 Y0 E2500.0
G1 Z0.4
G1 X30 Y0 E4000.0
; filament used [g] = 11.9
; estimated printing time (normal mode) = 1h 2m 3s
""".strip().splitlines()


def test_absolute_extrusion_totals():
    result = parse_gcode(ABSOLUTE)
    # Absolute E ends at 4000, having started from 0. Lengths are realistic
    # here because grams are rounded to 3dp: at toy lengths the rounding, not
    # the arithmetic, would decide whether the test passes.
    assert result.calculated_filament_mm == pytest.approx(4000.0)
    assert result.calculated_filament_grams == pytest.approx(filament_grams(4000.0), rel=1e-3)
    assert result.slicer_name == "OrcaSlicer 2.1.0"
    assert result.slicer_print_time_seconds == 3723
    assert result.layer_count == 2


RELATIVE = """
M83
G1 X10 E0.5
G1 X20 E0.5
G1 X30 E0.5
""".strip().splitlines()


def test_relative_extrusion_sums_each_move():
    result = parse_gcode(RELATIVE)
    assert result.calculated_filament_mm == pytest.approx(1.5)


RETRACTION = """
M83
G1 X10 E1.0
G1 E-5.0
G1 E5.0
G1 X20 E1.0
""".strip().splitlines()


def test_unretracting_is_not_consumption():
    """A retraction and its matching push-back deposit nothing.

    Counting every positive E move as material treats each un-retract as fresh
    filament. On a real print that overstated usage by 39% — the parser
    disagreed with the slicer by a third and the discrepancy looked like a
    slicer problem rather than an arithmetic one.

    Here 1.0 is laid down, 5.0 is withdrawn, 5.0 repays that withdrawal, and
    1.0 more is laid down: 2.0 total.
    """
    result = parse_gcode(RETRACTION)
    assert result.calculated_filament_mm == pytest.approx(2.0)


def test_partial_unretract_repays_before_depositing():
    lines = """
M83
G1 X10 E1.0
G1 E-5.0
G1 E7.0
""".strip().splitlines()
    # 5.0 of the 7.0 repays the retraction; 2.0 is new material, plus the 1.0.
    assert parse_gcode(lines).calculated_filament_mm == pytest.approx(3.0)


def test_layer_count_prefers_the_declared_total():
    lines = """
; total layer number: 40
M83
G1 Z0.2
G1 Z1.0
G1 Z0.4
""".strip().splitlines()
    # Z-hops would otherwise inflate the count; the file states the truth.
    assert parse_gcode(lines).layer_count == 40


def test_layer_change_markers_beat_counting_z_rises():
    lines = """
M83
G1 Z0.2
;LAYER_CHANGE
G1 Z0.6
G1 Z0.4
;LAYER_CHANGE
G1 Z0.6
""".strip().splitlines()
    # Four Z increases, two real layers.
    assert parse_gcode(lines).layer_count == 2


def test_g92_reset_does_not_create_phantom_extrusion():
    lines = """
M82
G1 X10 E5.0
G92 E0
G1 X20 E5.0
""".strip().splitlines()
    # Without honouring G92 the second move would look like -5 or +10.
    assert parse_gcode(lines).calculated_filament_mm == pytest.approx(10.0)


def test_per_tool_totals_for_multi_material():
    lines = """
M83
T0
G1 X10 E2.0
T1
G1 X20 E3.0
T0
G1 X30 E1.0
""".strip().splitlines()
    result = parse_gcode(lines)
    assert result.per_tool_filament_mm == {0: pytest.approx(3.0), 1: pytest.approx(3.0)}
    assert result.calculated_filament_mm == pytest.approx(6.0)


def test_travel_only_file_warns():
    result = parse_gcode(["G1 X10 Y10", "G1 X20 Y20"])
    assert result.calculated_filament_mm == 0
    assert any("no extrusion" in w.lower() for w in result.warnings)


def test_comments_do_not_count_as_moves():
    result = parse_gcode(["; G1 X10 E99.0", "G1 X10 E1.0 ; E5.0 in a comment", "M83"])
    assert result.calculated_filament_mm == pytest.approx(1.0)


class TestDuration:
    @pytest.mark.parametrize(
        "text,expected",
        [
            ("1h 2m 3s", 3723),
            ("2d 3h", 183600),
            ("45m", 2700),
            ("90", 90),
            ("nonsense", None),
        ],
    )
    def test_parse(self, text, expected):
        assert parse_duration(text) == expected


class TestConfidence:
    def test_close_agreement_is_high(self):
        level, reason = confidence_from_agreement(83.2, 83.5)
        assert level == "HIGH"
        assert "agree" in reason

    def test_disagreement_is_medium_and_states_the_gap(self):
        level, reason = confidence_from_agreement(83.2, 100.0)
        assert level == "MEDIUM"
        assert "%" in reason

    def test_missing_slicer_figure_is_medium(self):
        level, _ = confidence_from_agreement(83.2, None)
        assert level == "MEDIUM"

    def test_nothing_available_is_low(self):
        level, _ = confidence_from_agreement(None, None)
        assert level == "LOW"


class TestWaste:
    """Waste measured by feature and computed for colour changes (§52-§53)."""

    def test_multi_colour_slicer_total_is_not_just_the_first_filament(self):
        # Orca writes one figure per filament. Reading the first alone reported
        # a two-colour keychain as 3.02 g instead of 3.75 g.
        lines = [
            "; filament used [g] = 3.02, 0.73",
            "; total filament used [g] = 3.75",
        ]
        result = parse_gcode(lines)
        assert result.slicer_filament_grams == pytest.approx(3.75)
        assert result.slicer_filament_grams_per_tool == [3.02, 0.73]

    def test_per_tool_figures_are_summed_when_there_is_no_total(self):
        result = parse_gcode(["; filament used [g] = 1.50, 2.25"])
        assert result.slicer_filament_grams == pytest.approx(3.75)

    def test_features_are_classified_by_their_type_label(self):
        lines = """
M83
;TYPE:Custom
G1 X5 E1.0
;TYPE:Skirt
G1 X10 E2.0
;TYPE:Brim
G1 X20 E3.0
;TYPE:Outer wall
G1 X30 E10.0
;TYPE:Support
G1 X40 E4.0
;TYPE:Support interface
G1 X50 E1.0
;TYPE:Sparse infill
G1 X60 E5.0
""".strip().splitlines()
        r = parse_gcode(lines)
        grams = lambda mm: filament_grams(mm)  # noqa: E731
        assert r.waste["prime_line_g"] == pytest.approx(grams(1.0), abs=1e-3)
        assert r.waste["skirt_brim_g"] == pytest.approx(grams(5.0), abs=1e-3)
        assert r.waste["support_g"] == pytest.approx(grams(5.0), abs=1e-3)
        assert r.product_grams == pytest.approx(grams(15.0), abs=1e-3)
        assert r.total_grams == pytest.approx(grams(26.0), abs=1e-3)

    def test_purge_comes_from_the_flush_table_when_the_firmware_purges(self):
        # Kobra X: the purge moves are commented out of the file, so only the
        # slicer's flush table knows how much the printer will push out.
        lines = """
M83
T0
;TYPE:Outer wall
G1 X10 E10.0
T1
;;; G1 E20.43 F300
G1 X20 E5.0
; flush_volumes_matrix = 0,546,184,0
; flush_multiplier = 1
; filament_density = 1.24,1.24
""".strip().splitlines()
        r = parse_gcode(lines)
        assert r.tool_changes == 1
        assert r.waste["purge_basis"] == "flush volumes"
        # 546 mm3 of PLA at 1.24 g/cm3.
        assert r.waste["purge_g"] == pytest.approx(0.677, abs=1e-3)
        blue = next(row for row in r.per_tool if row["tool"] == 1)
        black = next(row for row in r.per_tool if row["tool"] == 0)
        assert blue["purge_g"] == pytest.approx(0.677, abs=1e-3), "purge is the incoming filament"
        assert black["purge_g"] == 0

    def test_flush_multiplier_scales_the_purge(self):
        lines = ["M83", "T0", "G1 X1 E1", "T1", "G1 X2 E1",
                 "; flush_volumes_matrix = 0,500,500,0", "; flush_multiplier = 1.5"]
        assert parse_gcode(lines).waste["purge_g"] == pytest.approx(0.75 * 1.24, abs=1e-3)

    def test_every_change_back_and_forth_is_purged(self):
        lines = ["M83", "T0", "G1 X1 E1", "T1", "G1 X2 E1", "T0", "G1 X3 E1",
                 "; flush_volumes_matrix = 0,100,200,0"]
        r = parse_gcode(lines)
        assert r.tool_changes == 2
        # 0->1 purges 100 mm3 of filament 1; 1->0 purges 200 mm3 of filament 0.
        assert r.waste["purge_g"] == pytest.approx(0.3 * 1.24, abs=1e-3)

    def test_reselecting_the_same_filament_is_not_a_change(self):
        lines = ["M83", "T0", "G1 X1 E1", "T0", "G1 X2 E1", "; flush_volumes_matrix = 0,100,100,0"]
        r = parse_gcode(lines)
        assert r.tool_changes == 0
        assert r.waste["purge_g"] == 0

    def test_a_printed_prime_tower_is_measured_not_computed_twice(self):
        lines = """
M83
T0
;TYPE:Outer wall
G1 X10 E10.0
T1
;TYPE:Prime tower
G1 X20 E4.0
; flush_volumes_matrix = 0,546,184,0
""".strip().splitlines()
        r = parse_gcode(lines)
        assert r.waste["purge_basis"] == "prime tower"
        assert r.waste["purge_g"] == pytest.approx(filament_grams(4.0), abs=1e-3)

    def test_changes_without_a_flush_table_warn_instead_of_guessing(self):
        r = parse_gcode(["M83", "T0", "G1 X1 E1", "T1", "G1 X2 E1"])
        assert r.waste["purge_basis"] == "unknown"
        assert r.waste["purge_g"] == 0
        assert any("flush volumes" in w for w in r.warnings)

    def test_a_file_without_type_labels_is_all_product(self):
        # Some slicers label nothing. That is not a file made entirely of waste.
        r = parse_gcode(["M83", "G1 X10 E10.0", "G1 X20 E5.0"])
        assert r.waste["total_g"] == 0
        assert r.product_grams == pytest.approx(filament_grams(15.0), abs=1e-3)

    def test_extrusion_before_the_first_label_is_priming_when_labels_exist(self):
        r = parse_gcode(["M83", "G1 X0 E3.0", ";TYPE:Outer wall", "G1 X10 E10.0"])
        assert r.waste["prime_line_g"] == pytest.approx(filament_grams(3.0), abs=1e-3)

    def test_each_filament_uses_its_own_density(self):
        # PETG at 1.27 purging into a PLA job must not be priced as PLA.
        lines = ["M83", "T0", "G1 X1 E10", "T1", "G1 X2 E10",
                 "; filament_density = 1.24,1.27", "; flush_volumes_matrix = 0,1000,1000,0"]
        r = parse_gcode(lines)
        assert r.waste["purge_g"] == pytest.approx(1.27, abs=1e-3)
